package net.objectof.actof.minion.components.handlers.style;


public enum HandlerCategory {

    ADAPTER, AUTHENTICATOR, AUTHORIZER, BRANCH, BROADCASTER, COLLECTOR, ENDPOINT, FORWARDER, GENERIC, HIERARCHY, INSTRUMENTATION, INTERFACE, PERSIST, QUEUE, REGISTER, ROUTER, SCHEDULE, SERVICE, STEP, STREAMING, TIMER, TRANSFORMER;

}
