package net.objectof.actof.minion.classpath.minionhandler;


public enum MinionHandlerCategory {

    ADAPTER, AUTHENTICATOR, AUTHORIZER, BRANCH, BROADCASTER, COLLECTOR, ENDPOINT, FORWARDER, GENERIC, HIERARCHY, INSTRUMENTATION, INTERFACE, PERSIST, QUEUE, REGISTER, ROUTER, SCHEDULE, SERVICE, STEP, STREAMING, TIMER, TRANSFORMER;

}
